pixelshop/api/urls.py
"""Api urls file."""

# Django
from django.urls import path

# Local
from . import views

app_name = 'api'
urlpatterns = [
    path(
        '',
        views.ApiIndexView.as_view(),
        name=views.ApiIndexView.name,
        ),
    path(
        'users/',
        views.UserListView.as_view(),
        name=views.UserListView.name,
        ),
    path(
        'users/<int:pk>/',
        views.UserDetailView.as_view(),
        name=views.UserDetailView.name,
        ),
    path(
        'pixelarts/',
        views.PixelArtListView.as_view(),
        name=views.PixelArtListView.name,
        ),
    path(
        'pixelarts/<int:pk>/',
        views.PixelArtDetailView.as_view(),
        name=views.PixelArtDetailView.name,
        ),
    path(
        'orders/',
        views.OrderListView.as_view(),
        name=views.OrderListView.name,
    ),
    path(
        'orders/<int:pk>/',
        views.OrderDetailView.as_view(),
        name=views.OrderDetailView.name,
        ),
]

pixelshop/pixelshop/urls.py
"""Pixelshop urls file."""

# Django
from django.urls import include
from django.urls import path

# Local
from .views import AboutusView
from .views import OrderCompleteView
from .views import ProductView
from .views import ProfileUpdateView
from .views import ProfileView
from .views import RegisterView
from .views import RegulationsView
from .views import ShopView

app_name = 'pixelshop'
urlpatterns = [
    path(
        'shop/',
        ShopView.as_view(),
        name='shop',
        ),
    path(
        'shop/<pk>/',
        ProductView.as_view(),
        name='product',
        ),
    path(
        'shop/ordercomplete/',
        OrderCompleteView,
        name='order-complete',
        ),
    path(
        'aboutus/',
        AboutusView.as_view(),
        name='aboutus',
        ),
    path(
        'profile/<pk>/',
        ProfileView.as_view(),
        name='profile',
        ),
    path(
        'profile/update/<pk>/',
        ProfileUpdateView.as_view(),
        name='profile-update',
        ),
    path(
        'register/',
        RegisterView,
        name='registration',
        ),
    path(
        'register/regulations/',
        RegulationsView.as_view(),
        name='regulations',
        ),
    path(
        'authenticate/',
        include(
            'django.contrib.auth.urls',
            ),
        ),
]

pixelshop/project/urls.py
# Django
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import include
from django.urls import path

# 3rd-party
from decorator_include import decorator_include

# Project
from pixelshop.views import HomePageView

urlpatterns = [
    path(
        'admin/',
        admin.site.urls,
        ),
    path(
        'pixelshop/',
        include('pixelshop.urls'),
        ),
    path(
        'api/',
        decorator_include(
            staff_member_required,
            'api.urls',
            ),
        ),
    path(
        '',
        HomePageView.as_view(),
        name='homepage',
        ),
]

pixelshop/api/views.py
"""Rest API Views file."""

# 3rd-party
from rest_framework import generics
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from rest_framework.reverse import reverse

# Project
from pixelshop.models import Order
from pixelshop.models import PixelArt
from pixelshop.models import User

# Local
from .filters import PixelArtFilter
from .serializers import OrderSerializer
from .serializers import PixelArtSerializer
from .serializers import UserSerializer


class ApiIndexView(GenericAPIView):
    """ApiIndexView class."""

    name = 'root-api'

    def get(self, request, *args, **kwargs):
        """Get method for ApiIndexView class."""
        return Response({
            'users': reverse(f'api:{UserListView.name}', request=request),
            'pixelarts': reverse(
                f'api:{PixelArtListView.name}',
                request=request,
                ),
            'orders': reverse(f'api:{OrderListView.name}', request=request),
        })


class UserListView(generics.ListCreateAPIView):
    """UserListView class.

    You can see all users and also you can create new one.
    """

    queryset = User.objects.all()
    serializer_class = UserSerializer
    name = 'user-list'
    filter_fields = [
        'username',
        'last_name',
        'email',
        'is_active',
        'is_staff',
        'is_superuser',
        ]
    search_fields = [
        'username',
        'first_name',
        'last_name',
        'email',
        ]
    ordering_fields = ['date_joined', 'last_login']

    def list(self, request):
        """List method for UserListView class."""
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = UserSerializer(
                page,
                context={'request': request},
                many=True,
                )
            return self.get_paginated_response(serializer.data)
        serializer = UserSerializer(
            queryset,
            context={'request': request},
            many=True,
            )
        return Response(serializer.data)


class UserDetailView(generics.RetrieveUpdateDestroyAPIView):
    """UserDetailView class."""

    queryset = User.objects.filter()
    serializer_class = UserSerializer
    name = 'user-detail'


class PixelArtListView(generics.ListCreateAPIView, PixelArtFilter):
    """PixelArtListView class.

    You can see all pixelarts and also you can create new one.
    """

    queryset = PixelArt.objects.filter()
    serializer_class = PixelArtSerializer
    name = 'pixelart-list'
    filter_class = PixelArtFilter
    search_fields = ['title', 'certificate_id', 'desc']
    ordering_fields = ['price']

    def list(self, request):
        """List method for PixelArtListView class."""
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = PixelArtSerializer(
                page,
                context={'request': request},
                many=True,
                )
            return self.get_paginated_response(serializer.data)
        serializer = PixelArtSerializer(
            queryset,
            context={'request': request},
            many=True,
            )
        return Response(serializer.data)


class PixelArtDetailView(generics.RetrieveUpdateDestroyAPIView):
    """PixelArtDetailView class."""

    queryset = PixelArt.objects.filter()
    serializer_class = PixelArtSerializer
    name = 'pixelart-detail'


class OrderListView(generics.ListCreateAPIView):
    """OrdertListView class.

    You can see all orders and also you can create new one.
    """

    queryset = Order.objects.filter()
    serializer_class = OrderSerializer
    name = 'order-list'
    filter_fields = ['status']
    search_fields = ['user', 'pixelart']
    ordering_fields = ['date_purchased']

    def list(self, request):
        """List method for OrderListView class."""
        queryset = self.filter_queryset(self.get_queryset())
        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = OrderSerializer(
                page,
                context={'request': request},
                many=True,
                )
            return self.get_paginated_response(serializer.data)
        serializer = OrderSerializer(
            queryset,
            context={'request': request},
            many=True,
            )
        return Response(serializer.data)


class OrderDetailView(generics.RetrieveUpdateDestroyAPIView):
    """OrderDetailView class."""

    queryset = Order.objects.filter()
    serializer_class = OrderSerializer
    name = 'order-detail'

pixelshop/templates/aboutus.html
{% extends 'base.html' %}
{% load static simple_tags %}
{% block content %}
    {% include 'navbar.html' %}
    <link rel="stylesheet" type="text/css" href="{% static '/website/css/aboutus.css' %}">
    <div class="content-about-us">
        <div class="container-fluid p-3 mb-5">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <h2 class="title-about">O NAS</h2>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row">
                <div class="col-6 ml-5 mr-5">
                    <div class="card mt-5" onclick="location.href = 'https://www.linkedin.com/in/maciej-szymborski-030070208/'">
                            <img class="card-img-top mt-5" src="{% static 'website/images/zdj_MS.jpg' %}" alt="szczur papiez">
                            <div class="card-body">
                                <h3 class="card-name mb-5">Maciej Szymborski</h3>
                                <h4 class="card-job-title mt-5 mb-5">Java Software Developer</h4>
                                <p class="card-desc mt-5 mb-5">Moim pierwszym językiem programowania który zachęcił mnie do programowania był Python lecz po czasie zainteresowała mnie Java. 
                                    Swoją przygodę z bardziej komerycyjnym programowaniem rozpocząłem z frameworkiem Spring. 
                                    W przyszłości planuje zostać Fullstack developerem rozwiązań webowych.</p>
                            </div>
                    </div>
                </div>
                <div class="col-6 ml-5 mr-5">
                    <div class="card mt-5" onclick="location.href = 'https://www.linkedin.com/in/szymon-śliwa-608255210/'">
                            <img class="card-img-top mt-5" src="{% static 'website/images/zdj_SS.jpg' %}" alt="Szymon Śliwa">
                            <div class="card-body">
                                <h3 class="card-name mb-5">Szymon Śliwa</h3>
                                <h4 class="card-job-title mt-5 mb-5">Python Software Developer</h4>
                                <p class="card-desc mt-5 mb-5">Zabawną sprawą jest to, że nigdy nie przepadałem za Pythonem. Zajęcia z wizualizacji danych sprawiały mi trudności. 
                                    Polubiłem ten język dopiero, kiedy miałem potrzebę automatyzacji wielu czynności. Hobbystycznie zacząłem bawić się w webscraping. Przygodę z 
                                    Django zacząłem na stażu podczas 2. roku studiów. Z racji ukończenia technikum informatycznego i pomyślnego zaliczenia egzaminów zawodowych 
                                    byłem obeznany z językiem znaczników HTML, php i językiem baz danych SQL. W przyszłości zamierzam rozszerzyć swoją wiedzę do stopnia, w którym 
                                    będę mógł nazywać się Fullstack developerem.
                                </p>
                            </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <h2 class="contact-title mt-5 mb-5">KONTAKT</h2>
                    <div class="card mt-5 mb-5">
                        <div class="card-body">
                            <h3>Email: pixelshopsupport@pixelshop.com</h3>
                            <hr>
                            <h3>Telefon: +48 xxx xxx xxx</h3>
                        </div>
                    </div>
                </div>
                <div class="col-3"></div>
            </div>
        </div>
    </div>
{% endblock content %}

pixelshop/templates/base.html
<!doctype html>
<html lang="pl" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="UTF-8">
        <title>Pixelshop</title>
        <meta name="description" content="PixelShop web page.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    <body>
        {% block page_title %}{% endblock page_title %}
        {% block content %}{% endblock content %}
        {% block extra_js %}{% endblock extra_js %}
        {% block modal %}{% endblock modal %}
    </body>
</html>

pixelshop/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'navbar.html' %}
    <link rel="stylesheet" type="text/css" href="{% static '/website/css/homepage.css' %}">
    <div class="content-main">
        <div class="container-fluid p-3 mb-5 mt-5">
            <div class="row">
                <div class="col-3"></div>
                <div class="col-6">
                    <h1>Witaj w Pixelshopie!</h1>
                </div>
                <div class="col-3"></div>
            </div>
            <div class="row">
                <div class="col-2"></div>
                <div class="col-8">
                    <p class="subtitle">Jeżeli chcesz dowiedzieć się o nas więcej zapraszamy do zakładki O NAS :)</p>
                </div>
                <div class="col-2"></div>
            </div>
        </div>
    </div>
{% endblock content %}

pixelshop/templates/navbar.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static '/website/css/navbar.css' %}">

<div class="sidebar">
  <div class="logo_content">
    <div class="logo">
      <i class='bx bxl-python' ></i>
      <div class="logo_name">PIXELSHOP</div>
    </div>
    <i class='bx bx-menu' id="btn"></i>
  </div>
  <ul class="nav_list">
    <li>
      <a href="{% url 'homepage' %}">
        <i class='bx bx-home-alt' ></i>
        <span class="links_name">Strona Glowna</span>
      </a>
      <span class="tooltip">Strona Glowna</span>
    </li>
    <li>
      <a href="{% url 'pixelshop:shop' %}">
        <i class='bx bx-store' ></i>
        <span class="links_name">Sklep</span>
      </a>
      <span class="tooltip">Sklep</span>
    </li>
    <li>
      <a href="{% url 'pixelshop:aboutus' %}">
        <i class='bx bx-info-circle' ></i>
        <span class="links_name">O nas/Kontakt</span>
      </a>
      <span class="tooltip">O nas/Kontakt</span>
    </li>
    {% if request.user.is_authenticated %}
    <li>
      <a href="{% url 'pixelshop:profile' pk=request.user.pk %}">
        <i class='bx bxs-user-detail' ></i>
        <span class="links_name">Profil</span>
      </a>
      <span class="tooltip">Profil</span>
    </li>
    {% endif %}
    {% if request.user.is_superuser %}
    <li>
      <a href="{% url 'api:root-api' %}">
        <i class='bx bx-data' ></i>
        <span class="links_name">Api</span>
      </a>
      <span class="tooltip">Api</span>
    </li>
    {% endif %}
  </ul>
  <div class="profile_content">
    <div class="profile">
      {% if request.user.is_authenticated %}
      <div class="profile_details">
        <i class='bx bxs-user' ></i>
        <div class="logged_user_details">
          <div class="name">{{ request.user.first_name }} {{ request.user.last_name }}</div>
          {% if request.user.is_superuser %}
          <div class="role">Admin</div>
          {% elif request.user.is_staff %}
          <div class="role">Staff</div>
          {% else %}
          <div class="role">User</div>
          {% endif %}
        </div>
      </div>
      <a href="{% url 'pixelshop:logout' %}"><i class='bx bx-log-out' id="log_in_out"></i></a>
      {% else %}
      <a href="{% url 'pixelshop:login' %}"><i class='bx bx-log-in' id="log_in_out"></i></a>
      {% endif %}
    </div>
  </div>
</div>
<script src="{% static '/website/js/navbar.js' %}" type="text/javascript"></script>

pixelshop/templates/pixelshop_homepage.html
{% extends 'base.html' %}
{% block content %}
    {% include 'navbar.html' %}
{% endblock content %}

pixelshop/templates/product.html
{% extends 'base.html' %}
{% load simple_tags %}
{% block content %}
    {% include 'navbar.html' %}
    <div class="container p-3 mt-3 mb-5 shadow-sm bg-white">
        <div class="row">
            <div class="col-4">
                <img class="border border-dark" src="{{ object.file|redirect_slashes }}" width="400" height="400" alt="Card image of product {{ object.title }}">
            </div>
            <div class="col-7">
                <div class="row mt-5">
                    <span><b>Nazwa:</b> {{ object.title }}</span>
                </div>
                <div class="row">
                    <span><b>Opis:</b> {{ object.desc }}</span>
                </div>
                <div class="row">
                    <span><b>Cena:</b> {{ object.price.amount }} {{ object.price.currency }}</span>
                </div>
                <div class="row mt-3">
                    {% if request.user.is_authenticated %}
                        <div id="paypal-button-container"></div>
                    {% else %}
                        <a href="{% url 'pixelshop:login' %}" class="btn btn-danger">Aby dokonać zakupu musisz się zalogować!</a>
                    {% endif %}
                </div>
            </div>
            <div class="col-1"></div>
        </div>
    </div>
    <script src="https://www.paypal.com/sdk/js?client-id=Aa9TEsqgnE--lM0JLwqAdlIEj4wtvvvrJJ8346MNaaydTGVgEvRwV8Mn4qiE5wT9pg13apkVYGUtoo31&currency={{ object.price.currency }}&disable-funding=credit"></script>
    <script>
        function getCookie(name) {
		    var cookieValue = null;
		    if (document.cookie && document.cookie !== '') {
		        var cookies = document.cookie.split(';');
		        for (var i = 0; i < cookies.length; i++) {
		            var cookie = cookies[i].trim();
		            if (cookie.substring(0, name.length + 1) === (name + '=')) {
		                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
		                break;
		            }
		        }
		    }
		    return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');
	 	var total = '{{ object.price.amount }}'
	 	var productId = '{{ object.pk }}'
        var buyerId = '{{ request.user.pk }}'
	 	function completeOrder(){
	 		var url = "{% url 'pixelshop:order-complete' %}"
	 		fetch(url, {
	 			method:'POST',
	 			headers:{
	 				'Content-type':'application/json',
	 				'X-CSRFToken':csrftoken,
	 			},
	 			body:JSON.stringify({'productId':productId, 'buyerId':buyerId})
	 		})
	 	}
        paypal.Buttons({
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{ 
                        amount: {
                            value: total
                        }
                    }]
                });
            },
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    completeOrder()
                    alert('Transakcja dokonana przez ' + details.payer.name.given_name + '.');
                });
            }
        }).render('#paypal-button-container');
    </script>
{% endblock content %}

pixelshop/templates/profile.html
{% extends 'base.html' %}
{% load simple_tags %}
{% block content %}
    {% include 'navbar.html' %}
    <div class="container shadow-sm p-3 mb-5 mt-5 bg-white">
        {% with userpk=request.get_full_path|get_pk %}
            {% if userpk == request.user.pk %}
            <form>
                <fieldset disabled>
                    <div class="row mb-3">
                        <div class="col-10">
                            <legend>{{ object.username }}</legend>
                        </div>
                        <div class="col-2">
                            <a href="{% url 'pixelshop:profile-update' pk=request.user.pk %}">
                                <button type="button" class="btn btn-primary">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                         <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"></path>
                                    </svg>
                                    Edytuj profil
                                </button>
                            </a> 
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">
                            <label for="email" class="form-label">Email</label>
                        </div>
                        <div class="col-6">
                            <input type="text" id="email" class="form-control" placeholder="{{ object.email }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">
                            <label for="first_name" class="form-label">Imię</label>
                        </div>
                        <div class="col-6">
                            <input type="text" id="first_name" class="form-control" placeholder="{{ object.first_name }}">
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-6">
                            <label for="last_name" class="form-label">Nazwisko</label>
                        </div>
                        <div class="col-6">
                            <input type="text" id="last_name" class="form-control" placeholder="{{ object.last_name }}">
                        </div>
                    </div>
                </fieldset>
              </form>
            {% else %}
                <div class="row">
                    <div class="col-12">
                        <p>Cwany jesteś, ale nic tu nie znajdziesz :)</p>
                    </div>
                </div>
            {% endif %}
        {% endwith %}
    </div>
{% endblock content %}

pixelshop/templates/profile_update.html
{% extends 'base.html' %}
{% load simple_tags %}
{% block content %}
    {% include 'navbar.html' %}
    <div class="container shadow-sm p-3 mb-5 mt-5 bg-white">
        <div class="row mt-5">
            <div class="col-12">
                {% with userpk=request.get_full_path|get_pk %}
                    {% if userpk == request.user.pk %}
                        <form method="post">
                            <legend>Edycja profilu użytkownika:</legend>
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_email" class="form-label">Email:</label>
                                <input type="email" name="email" maxlength="150" class="form-control" id="id_email" value="{{ object.email }}">
                            </div>
                            <div class="mb-3">
                                <label for="id_first_name" class="form-label">Imię:</label>
                                <input type="text" name="first_name" maxlength="150" class="form-control" id="id_first_name" value="{{ object.first_name }}">
                            </div>
                            <div class="mb-3">
                                <label for="id_last_name" class="form-label">Nazwisko:</label>
                                <input type="text" name="last_name" maxlength="150" class="form-control" id="id_last_name" value="{{ object.last_name }}">
                            </div>
                            <input type="submit" class="btn btn-primary" value="Zapisz zmiany">
                        </form>
                    {% else %}
                        <p>Cwany jesteś, ale nic tu nie znajdziesz :)</p>
                    {% endif %}
                {% endwith %}            
          </div>
        </div>
    </div>
{% endblock content %}

pixelshop/templates/shop.html
{% extends 'base.html' %}
{% load static simple_tags %}
{% block content %}
    {% include 'navbar.html' %}
    <link rel="stylesheet" type="text/css" href="{% static '/website/css/shop.css' %}">
    <div class="content-shop">
      <div class="container-fluid p-3 mb-5 mt-5">
      <div class="row">
        {% for object in object_list %}
          <div class="col-6 col-sm-6 col-lg-4 col-md-6 col-xl-3">
              <div class="card">
                <a href="{% url 'pixelshop:product' pk=object.pk %}">
                  <img class="card-img-top" src="{{ object.file|redirect_slashes }}" alt="Card image of product {{ object.title }}">
                </a>
                <div class="card-body">
                  <h5 class="card-title">{{ object.title }}</h5>
                  <h6 class="card-price">{{ object.price.amount }} {{ object.price.currency }}</h6>
                  <p class="card-text">{{ object.desc }}</p>
                  <!-- <a href="#" class="btn btn-primary">KUP</a> -->
                </div>
              </div>
            </div>
          {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}